### ISSUE TITLE
Floating point precision can cause misformatted winrates in stats command

### ISSUE THREAD

**Issue by ellomenop** [OpenATBP/BMO#1]
https://github.com/OpenATBP/BMO/blob/ae068cf1171d8e77f692d8ac7beb10f3b5d320b1/discordjs/commands/stats.js#L39

Change this line to round / format after all the math to fix. 

See discord for examples of 56.000000000001% for 5 wins out of 9 games as an example

**Comment by Darklit** [comment]
Fixed in commit a536465350344e274d5f4e7e0d0a79414f69a35a
